# Copyright 2017 the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: Namespace
metadata:
  name: example-app
  labels:
    app: example

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
  namespace: example-app
  labels:
    app: example
spec:
  # Optional:
  # storageClassName: <YOUR_STORAGE_CLASS_NAME>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  namespace: example-app
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
      annotations:
        backup.velero.io/backup-volumes: my-pvc
    spec:
      volumes:
        - name: my-pvc
          persistentVolumeClaim:
           claimName: my-pvc
      containers:
      - image: ubuntu:bionic
        name: fsfreeze
        volumeMounts:
          - mountPath: "/opt/my-pvc"
            name: my-pvc
            readOnly: false
        command:
          - "/bin/bash"
          - "-c"
          - "sleep infinity"
      securityContext:
        runAsUser: 1001
        fsGroup: 1001

