---
- name: Deploy nginx-ingress with helm 
  hosts: localhost
  gather_facts: no
  vars:
    helm_chart: bitnami/nginx-ingress-controller
    helm_chart_version: 5.6.14
    helm_deployment_name: monitoring-ingress
    namespace: monitoring
  tasks:
    - name: helm_repo_add
      shell: |
        helm repo add bitnami https://charts.bitnami.com/bitnami     
    - name: helm_repo_update
      shell: |
        helm repo update
    - name: install_deployment
      shell: |
        helm upgrade {{ helm_deployment_name }} {{ helm_chart }} \
          --version {{ helm_chart_version }} \
          -n {{ namespace }} \
          -f ../nginx-ingress/values.yml \
          --install --create-namespace
